### PR TITLE
Vite 5 support

### LINKED ISSUE #126: Upgrade compatibility with Vite 5
[Vite 5 got released](https://vitejs.dev/blog/announcing-vite5) and this plugin is missing compatibility with the version 5.

From first look, it seems like everything should work with version 5 and only the peer dependency needs to be added. For more information there is the [migration guide](https://vitejs.dev/guide/migration)

### PR DESCRIPTION
**Pull request by birkskyum**
Closes #126 

I updated the examples to have separate examples for Vite 3, 4 and 5, and checked they all work.

I added vite 5 to the peer deps:

  "peerDependencies": {
    "solid-js": "^1.7.2",
    "vite": "^3.0.0 || ^4.0.0 || ^5.0.0"
  },

### CODE REVIEW

**Comment by Grabber** [comment]
Highest priority!

**Comment by carere** [comment]
For info, with vite 5, the solid-start-deno adapter does not work when building the project.
Getting an error with `vite:define`

**Comment by birkskyum** [comment]
Yeah, i found some issues with adapters as well https://github.com/solidjs/solid-start/pull/1124 , but figured it's probably more feasible to await the new Nitro/Vinxi version and then have a look at it.

**Comment by nilshelmig** [comment]
@ryansolid @birkskyum What's missing to get this merged?

**Comment by birkskyum** [comment]
I'm not currently aware of anything missing.

**Comment by birkskyum** [comment]
I don't know if this will fix the solid-start-cloudflare-pages adapter. It'll be replace with [this](https://nitro.unjs.io/deploy/providers/cloudflare#cloudflare-pages) adapter soon, so it might help.

**Comment by nilshelmig** [comment]
> I'm also getting errors from `vite:define` using Vite 5 and `solid-start-cloudflare-pages@0.3.10`:
> 
> ```
> user@MBP my-project % pnpm build
> 
> > my-solid-app@0.1.0 build /Users/user/my-project
> > solid-start build
> 
>  solid-start build 
>  version  0.3.10
> (node:93293) ExperimentalWarning: The Ed25519 Web Crypto API algorithm is an experimental feature and might change at any time
> (Use `node --trace-warnings ...` to show where the warning was created)
>  adapter  cloudflare-pages
> 
> solid-start building client...
> vite v5.0.4 building for production...
> ✓ 4 modules transformed.
> [vite:define] Transform failed with 1 error:
> error: Invalid define value (must be an entity name or valid JSON syntax): (() => {})
> file: /Users/user/my-project/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.1_@solidjs+router@0.9.1_solid-js@1.8.6_solid-start-clou_ykgf2egikbvfaqjxxzhhreqmsa/node_modules/solid-start/entry-client/mount.tsx
> 🐼 error [❌] Transform failed with 1 error:
> error: Invalid define value (must be an entity name or valid JSON syntax): (() => {})
> ```

Is this related to `vite-plugin-solid`? For me it seems, this relates to `solid-start-cloudflare-pages`. If so, consider reporting the bug there :slightly_smiling_face:

**Comment by CreativeTechGuy** [comment]
Can/Should this PR also fix the deprecated APIs that were being used? I know we have been getting spammed with warnings when running tests as a result of [registerNodeLoader](https://github.com/solidjs/vite-plugin-solid/blob/7e667ad0bb05ba55e0a4a3e185ecc7e3e3535e4f/src/index.ts#L338). This was removed in vitest 1.0 [here](https://github.com/vitest-dev/vitest/pull/4371) and since Vite 5 and Vitest 1 are tightly coupled, it'd make sense to fix that here.

**Comment by birkskyum** [comment]
How do I do that? Is it a matter of swapping registerNodeLoader with optimizer as indicated [here](https://github.com/vitest-dev/vitest/issues/3596#issue-1760920776):

```json
deps: { registerNodeLoader: true },
```

replaced with:

```json
deps: { optimizer: {
ssr: {enabled: true},
web: {enabled: true}
} },
```

Or should `deps: { registerNodeLoader: true },` just be removed, since the `enabled: true` is the default values anyway?

**Comment by CreativeTechGuy** [comment]
@birkskyum I'm not sure. It might work just by being removed. The docs you found seem to point to just removing it.

**Comment by birkskyum** [comment]
Think so too - guess there's a reason for this issue being opened:
- https://github.com/vitest-dev/vitest/issues/3524

I have removed it.

**Comment by ryansolid** [comment]
Thanks everyone. Sorry for taking my time here. Often with new versions we hit some fun issues..So was just letting it breathe.

**Pull request merged**
