### PR TITLE
Update merge-anything to 5.0.0

### LINKED ISSUE #28: invalid merge-anything version
**Describe the bug**
I bootstrapped new project using solid-start but when trying to start it I get error

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:

1. `mkdir my-app`
2. `cd my-app`
3. `npm init solid@next`
4. `npm install`
6. `npm run dev`

**Expected behavior**
No error, example app runs correctly.

**Actual behavior**
```
> dev
> solid-start dev

failed to load config from C:\dev\solid\vite.config.ts
error when starting dev server:
file:///C:/dev/solid/node_modules/vite-plugin-solid/dist/esm/index.mjs:5
import { mergeAndConcat } from 'merge-anything';
         ^^^^^^^^^^^^^^
SyntaxError: Named export 'mergeAndConcat' not found. The requested module 'merge-anything' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'merge-anything';
const { mergeAndConcat } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (C:\dev\solid\node_modules\vite\dist\node\chunks\dep-f5552faa.js:75080:31)
    at async resolveConfig (C:\dev\solid\node_modules\vite\dist\node\chunks\dep-f5552faa.js:74656:28)
    at async createServer (C:\dev\solid\node_modules\vite\dist\node\chunks\dep-f5552faa.js:60326:20)
    at async CAC.<anonymous> (C:\dev\solid\node_modules\vite\dist\node\cli.js:688:24)
```

**Additional context**
Forcing vite-plugin-solid to use just released merge-anything@5.0.0 fixes the issue:

1. Make sure you're using npm that supports overrides: `npm i -g npm@^8.3.0`
2. Apply this change:
    ```diff
    diff --git a/package.json b/package.json
    index f4e45af..16a8418 100644
    --- a/package.json
    +++ b/package.json
    @@ -18,5 +18,8 @@
       },
       "engines": {
         "node": ">=14"
    +  },
    +  "overrides": {
    +    "merge-anything": "5.0.0"
       }
     }
    ```
3. `rm -rf package-lock.json node_modules`
4. `npm install`
6. `npm run dev`
```
> dev
> solid-start dev

Pre-bundling dependencies:
  solid-js
  solid-js/web
  solid-js/store
  solid-js/html
  solid-js/h
(this will be run only when your dependencies or config have changed)

  vite v2.7.13 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 806ms.

  > Inspect: http://localhost:3000/__inspect/

  > Routes:
     http://localhost:3000/
```

**My env:**
```
$ npx envinfo --system --npmPackages --binaries --browsers

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 6.81 GB / 15.86 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.69)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    node-fetch: ^2.6.6 => 2.6.7
    solid-app-router: ^0.2.1 => 0.2.1
    solid-js: ^1.3.3 => 1.3.3
    solid-meta: ^0.27.3 => 0.27.3
    solid-start: next => 0.1.0-alpha.55
    solid-start-node: next => 0.1.0-alpha.55
    typescript: ^4.4.3 => 4.5.5
    vite: ^2.7.11 => 2.7.13
```

### PR DESCRIPTION
**Pull request by bgoscinski**
Fixes #28 by updating to [merge-anything@5.0.0](https://github.com/mesqueeb/merge-anything/releases/tag/v5.0.0). Since you declare that 

> This module 100% esm compatible. As per this document it is strongly recommended to have at least the version 14.13.0 of node installed.

I think this is not a breaking change

### CODE REVIEW

**Comment by amoutonbrady** [comment]
Thank you!

**Comment by bgoscinski** [comment]
@amoutonbrady glad I could help :)
When do you plan to release a new version with this change?

**Comment by amoutonbrady** [comment]
Oh that was release last night actually! Available in 2.2.5 :)

**Comment by bgoscinski** [comment]
Oh I see! I was checking https://github.com/solidjs/vite-plugin-solid/releases 😅

**Pull request merged**
